### ISSUE TITLE
RuntimeError: einsum(): subscript f has size 256 for operand 1 which does not broadcast with previously seen size 128

### ISSUE THREAD

**Issue by huzimun** [Applied-Machine-Learning-Lab/HAMUR#3]
According to the readme.md file, when I run the command "python test_kuairand.py --model_name mlp_adp --epoch 200 --device cpu --seed 2022", the following errow will occur:
RuntimeError: einsum(): subscript f has size 256 for operand 1 which does not broadcast with previously seen size 128
![image](https://github.com/Applied-Machine-Learning-Lab/HAMUR/assets/78075933/620afa22-51f9-43cc-8417-cc4a20373d59)

There may be something wrong with the settings of parameters.

**Comment by Xiaopengli1** [comment]
Just fixed this issue, you could run it again. Many thanks for your attention to our work.
